mitodl/learn-ai

docker-compose.apps.yml, docker-compose.services.yml
None
Removes the compose profiles. We don't need them here.
`docker compose up` without COMPOSE_PROFILES in your `.env` file.
=> remove compose profiles

ai_chatbots/chatbots.py, ai_chatbots/tools.py
N/A
Moves the instructions/details on how to pick search parameters for the recommendation agent to the relevant docstrings in the search tool.
You will need `OPENAI_API_KEY` set in your .env file to the same value as mit-learn on RC.
Also set `AI_DEBUG=True`
Go to http://ai.open.odl.local:8003 and send requests like these; check the network response, in the developer tab, the search parameters should be in a comment at the bottom of the response. Make sure it is picking appropriate parameters:
> "I want free courses or programs about ecology"
> "Are there any economics courses from Sloan that offer certificates?"
> "I'm looking for podcasts about climate change".
Also try off-topic questions like these, it should tell you that it is only supposed to answer questions about MIT learning …
=> Move details/instructions on search parameters to the tool docstrings

frontend-demo/src/app/page.tsx
N/A
Fixes the chat UI height in learn-ai
Before fix (main branch):
After fix (this branch):
Go to http://ai.open.odl.local:8003 - it should look like the last screenshot above, not the first.
=> Fix chat UI height

Dockerfile
Closes https://github.com/mitodl/hq/issues/6880
This PR takes the build argument `GIT_REF` in the `Dockerfile` and deposits it in the image under `/src/staticfiles/hash.txt`
- Build a test image with `docker build . -f Dockerfile --build-arg GIT_REF=4bad616448f9c2f6840c96ae77b1efe8fcb644ce -t web-test`
- Run `docker run --rm -it --entrypoint bash web-test`
- Run `cat /src/staticfiles/hash.txt` and verify that the commit hash matches what was passed in
=> add git hash to docker images

Dockerfile
Follow up for https://github.com/mitodl/learn-ai/pull/85
This fixes the path of `hash.txt` to be in the `/src/static` directory, so it can be picked up by `collectstatic`, and makes sure the directory exists before doing so.
- Build a test image with `docker build . -f Dockerfile --build-arg GIT_REF=4bad616448f9c2f6840c96ae77b1efe8fcb644ce -t web-test`
- Run `docker run --rm -it --entrypoint bash web-test`
- Run `cat /src/static/hash.txt` and verify that the commit hash matches what was passed in
=> fix git hash path

main/asgi.py
N/A
Sentry was not picking up any data from the asgi endpoints for learn-ai.  This should fix that.
- Set `SENTRY_DSN=<TBD_ask_devops>` in your backend.local.env file
- Run `docker compose up ` and go to http://ai.open.odl.local:8003
- Ask some questions.
- Go to dashboard.heroku.com, check the learn-ai-qa project, you should see some data from `/http/recommendation_agent` urls.
https://docs.sentry.io/platforms/python/integrations/asgi/
=> Make sentry work for asgi endpoints too

main/urls.py
Closes https://github.com/mitodl/hq/issues/6959
Fixes an error due to django debug toolbar urls not being included in local environments (where debug is True)
1. note that locally on current main hitting localhost:8001 results in a 500
2. checkout this branch
3. error should not be thrown
=> adding debug toolbar urls

ai_chatbots/chatbots.py, ai_chatbots/chatbots_test.py, users/middleware.py
Closes https://github.com/mitodl/hq/issues/7035
- Refactors the chatbot posthog event code into its own function, and calls it from both the base `get_completion` function and the Tutorbot overrriden implementation.
- Adds some Tutorbot metadata for the posthog event (edx_module_id, block_siblings, problem, problem_set)
- Changes an error logging statement to a debug statement
- Set `POSTHOG_*` env values to the same as RC.
- Ask both the recommendation bot and tutor bot some questions, then log in to posthog and check that they eventually show up (may take a few minutes) with correct values for the question, answer, and metadata.
=> Send posthog event with metadata for tutorbot

ai_chatbots/chatbots_test.py, ai_chatbots/tools.py, main/settings.py
Closes https://github.com/mitodl/hq/issues/7044
Changes course links returned by the recommendation bot to resource drawer links in MIT Learn
- Ask the recommendation bot for some courses/videos/podcasts etc
- Click the links on the results, they should go to the correct MIT Learn resource drawer
=> Change recommendation bot course links to resource drawer links

frontend-demo/src/services/openedx/client.ts
https://github.com/mitodl/hq/issues/7090
Include credentials in sandbox requests
This could be tested locally with a local OpenEdx instance instead of the openedx proxy used by default.
If you want to test this locally, my suggestion is:
1. docker compose up
2. Go to http://ai.open.odl.local:8003/?tab=VideoGPT
3. Copy the network call to `/openedx_proxy/api/user/v1/me` as a `fetch`:
4. Paste it into the console at https://learn-ai-qa.ol.mit.edu/, changing the url to `
https://courses-qa.mitxonline.mit.edu/api/user/v1/me`. It should succeed. (200 not 401, either including your user data or indicating you're anonymous).
=> include credentials in edx requests

main/constants.py, main/consumer_throttles.py, main/models.py, main/models_test.py
Closes https://github.com/mitodl/hq/issues/7107
Overrides the `ConsumerThrottleLimit.save` function to clear the throttle cache.
- Change the existing `ConsumerThrottleLimit` with key `recommendation_bot` to 1/hour for auth and anon users at http://ai.open.odl.local:8002/admin/main/consumerthrottlelimit/
- Try to make more 2+ requests in short order from the home page.  After the 1st you should get a message like "Please try again in 59m"
- Go back to http://ai.open.odl.local:8002/admin/main/consumerthrottlelimit/ and change the interval to "minute"
- Try to make more requests, you should get a message like "Please try again in 52s"
=> Clear throttle cache on ConsumerThrottleLimit.save

ai_chatbots/api.py, ai_chatbots/chatbots.py, ai_chatbots/chatbots_test.py, ai_chatbots/consumers.py, ai_chatbots/consumers_test.py, ai_chatbots/factories.py, ai_chatbots/serializers.py, ai_chatbots/tools.py, ai_chatbots/tools_test.py, env/frontend.env, env/shared.env, frontend-demo/src/app/(home)/RecommendationContent.tsx, frontend-demo/src/app/(home)/SelectSearchUrl.tsx, frontend-demo/src/app/(home)/util.ts, main/settings.py
Closes https://github.com/mitodl/hq/issues/7171
Adds search url to the agent state of the RecommendationBot and updates the sandbox UI to specify it.
- Set `AI_DEBUG=True`
- With the network tab open, try the sandbox UI with all 3 search url options (none selected, elasticsearch, vector).  After each request, check the metadata at the end of the response for `search_url`, it should be the vector endpoint if you selected "Vector" otherwise it should be the elasticsearch endpoint.
The default remains elasticsearch; if we decide the vector search provides better results, I'll create an ol-infrstructure PR to change it.
=> Option to override the default recommendation bot search url 

env/frontend.env, frontend-demo/src/app/(home)/AssessmentContent.tsx, frontend-demo/src/app/(home)/RecommendationContent.tsx, frontend-demo/src/app/(home)/SyllabusContent.tsx, frontend-demo/src/app/(home)/VideoContent.tsx, frontend-demo/src/app/(home)/util.ts
Closes https://github.com/mitodl/hq/issues/7231
This PR makes it so:
1. A new thread is started when user changes AI model OR a new thread is started when user clicks "Start new thread"
2. The visible chat history clears when (1) occurs.
- **NOTE:** For resource-dependent chats (e.g., syllabus bot) changing the resource also creates a new thread. However, this does not clear the visible chat history right now.
- @Ferdi we could clear the visible chat history in this case if desirable. My rationale was that leaving it visible makes it easier to compare quality of responses.
However, there is currently no way to select a previously active thread.
https://github.com/user-attachments/assets/3b32d6e3-6085-4c80-9291-381e0ce10198
1. Visit http://ai.open.odl.local:8003/ and select any tab …
=> Start new thread when changing model in sandbox

README.md
Related to https://github.com/mitodl/hq/issues/7192
Adds a section to the README describing how to integrate langsmith.
Follow the instructions, determine if they are accurate and easy enough to follow.
=> Add langsmith integration to the README

ai_chatbots/chatbots_test.py, ai_chatbots/management/commands/update_prompt.py, ai_chatbots/prompts.py
Closes https://github.com/mitodl/hq/issues/7163
- Adds "your name is Tim" to the recommendation, syllabus, and video bot system prompts.
- Adds a mgmt command to update system prompts in langsmith, with user confirmation required if the prompt already exists in langsmith with a different value.
- If you haven't done so already, set up langsmith integration as described [here](https://github.com/mitodl/learn-ai/blob/58be8feb76c4bc7a4b4216291e7805b0456dd717/README.md#langsmith-integration).
- Run these management commands:
```
./manage.py update_prompt --prompt recommendation
./manage.py update_prompt --prompt syllabus
./manage.py update_prompt --prompt video_gpt
```
If these prompts already exist in your langsmith account, you should be shown the current and proposed prompt value and you …
=> Adjust chatbot system prompts to tell the LLM its name is Tim

ai_chatbots/prompts.py
Closes https://github.com/mitodl/hq/issues/7411
Updates the default prompts for the syllabus and video bots, clarifying that the search tool
will already have the resource/transcript id (via agent state).
- Go to https://learn.mit.edu/?resource=16469&syllabus= and ask Tim the question "How good is this class" for one of the courses.  You will likely get a response like this: "I apologize, but I notice that your question is quite general. To help you get information about a specific class, I'll need to know which class you're interested in."
- Go to https://rc.learn.mit.edu/?resource=17394&syllabus= where these prompt changes have already been applied via langsmith.  Ask the same question.  It should respond with "Let me search for ...." and then provide an answer based on search results.
=> Tweak the default syllabus/video system prompts, to avoid LLM confusion over resource id

ai_chatbots/api.py, ai_chatbots/api_test.py, ai_chatbots/chatbots.py, ai_chatbots/chatbots_test.py, ai_chatbots/prompts.py, ai_chatbots/tools.py
Closes https://github.com/mitodl/hq/issues/6542
- Adds the `search_content_files` tool to the list of tools available to the recommendation bot, and tweaks the system prompt to provide guidance on when to use it.
- Adjusts the summarization node/function to work more appropriately (noticed some issues during testing, since the trigger to use it was hit more often due to the greater # of tokens used up by the content files tool).
Ask for course recommendations, then ask for some detailed info about 1 or more of the courses (how is it graded, are there any class projects, etc).  Keep the conversation going for awhile to ensure the summarization is hit, responses seem reasonable, and no exceptions occur.
I needed to make some changes to the summarization code, because it assumed one tool …
=> Enable the recommendation bot to search for specific resource details

ai_chatbots/chatbots.py, ai_chatbots/management/commands/clear_prompt_cache.py, ai_chatbots/management/commands/update_prompt.py, ai_chatbots/prompts.py, ai_chatbots/prompts_test.py, ai_chatbots/serializers.py, ai_chatbots/urls.py, ai_chatbots/views.py, ai_chatbots/views_test.py, env/backend.env, frontend-demo/api/src/generated/v0/api.ts, frontend-demo/src/app/(home)/AssessmentContent.tsx, frontend-demo/src/app/(home)/BaseChatContent.tsx, frontend-demo/src/app/(home)/RecommendationContent.tsx, frontend-demo/src/app/(home)/SelectPrompt.tsx, frontend-demo/src/app/(home)/SyllabusContent.tsx, frontend-demo/src/app/(home)/VideoContent.tsx, frontend-demo/src/services/ai/index.ts, frontend-demo/src/services/ai/prompts/queries.ts, frontend-demo/src/services/ai/user/queries.ts, openapi/specs/v0.yaml
Closes https://github.com/mitodl/hq/issues/7506
- Adds an API endpoint for retrieving the system prompts of 3 chatbot agents (recommendation, syllabus, video GPT)
- Modifies the recommendation, syllabus, and video chatbot tabs to include a textarea field for sending a custom system prompt to each chatbot.  The field is prepopulated with the default prompt on load. 
Backend:
- Go to http://ai.open.odl.local:8005/api/v0/prompts/ - you should get a list of prompts for 3 chatbots (names and values)
- Go to http://ai.open.odl.local:8005/api/v0/prompts/syllabus/ - you should get the prompt name/value for the syllabus bot
- Go to http://ai.open.odl.local:8005/api/v0/prompts/fake/ - you should get a 404
- The endpoint should be included at http://ai.open.odl.local:8005/api/v0/schema/swagger-ui/ …
=> AI system prompts endpoint

ai_chatbots/serializers.py, ai_chatbots/serializers_test.py, main/settings.py
closes https://github.com/mitodl/hq/issues/7620
Users can create expensive llm calls by pasting large amounts of text in the message box. This pr limits user messages to 6000 characters
Go to the recommendation bot. Paste a long message (a wikipedia article that's longer than 6000 characters for example) in the message box. The bot should not break. From the shell run
```
from ai_chatbots.models import *
DjangoCheckpoint.objects.last().__dict__
```
The last human message should be truncated to 6000 characters
Paste the long message into the tutorbot. The bot should not break .
```
TutorBotOutput.objects.last().__dict__
```
should show the human message truncated to 6000 characters
=> limit message length

main/authentication_test.py
Related to https://github.com/mitodl/learn-ai/pull/14
Removes the use of `pytz` in a unit test, replaces it with `zoneinfo`.
This should fix the failing test in https://github.com/mitodl/learn-ai/pull/14
Tests should pass
=> Remove pytz from unit test

ai_chatbots/chatbots.py, ai_chatbots/chatbots_test.py, ai_chatbots/consumers.py, ai_chatbots/consumers_test.py, ai_chatbots/routing.py, ai_chatbots/serializers.py, ai_chatbots/urls.py, ai_chatbots/views.py, frontend-demo/api/src/generated/v0/api.ts, frontend-demo/src/app/(home)/CanvasAssessmentContent.tsx, frontend-demo/src/app/(home)/ChatTabs.tsx, frontend-demo/src/services/ai/urls.ts, main/settings.py, openapi/specs/v0.yaml, poetry.lock, pyproject.toml
closes https://github.com/mitodl/hq/issues/7944
This pr creates a canvas version of the Tutorbot UI
Go to http://ai.open.odl.local:8003/?rec_prompt=&tab=CanvasAssessmentGPT
You should be able to update the course run. Currently 14566-kaleba:20211202+canvas is the only course run with problem files. If you change it to something else the problem selection dropdown will be empty. If you select 14566-kaleba:20211202+canvas again after selecting something else the problem dropdown will be repopulated.
You should be able to select a problem set from the dropdown.
You should  be able to chat with the tutor about the problem set. If you check your networks tab in developer tools you should see a request to /canvas_tutor_agent/ with the correct problem_set_title and run_readable_id in the params …
=> canvas tutorbot

ai_chatbots/api.py, ai_chatbots/api_test.py, ai_chatbots/chatbots.py, ai_chatbots/chatbots_test.py
Closes https://github.com/mitodl/hq/issues/7957
Refactors how chatbot calls are sent to Posthog, so that their costs can be calculated.
https://posthog.com/docs/ai-engineering/observability
- Set the following env variables, using RC values:
```
POSTHOG_API_HOST=https://app.posthog.com
POSTHOG_PERSONAL_API_KEY=<secret>
POSTHOG_PROJECT_API_KEY=<secret>
POSTHOG_PROJECT_ID=<id>
POSTHOG_ENABLED=True
```
- Restart containers
- Use a few of the chatbots, including the tutorbot and at least 1 other.
- Log into Posthog, go to "Activities".  Make another column visible ("botName") and then filter event by "AI Trace (LLM)".  You should see a row for every chat session.
- Go to "LLM observability".  Then click on the "Traces" tab (chat sessions) and "Generations" tab (messages).  Each row should …
=> Track AI costs in Posthog

ai_chatbots/chatbots_test.py, ai_chatbots/prompts.py, ai_chatbots/tools.py, ai_chatbots/tools_test.py
Related to https://github.com/mitodl/hq/issues/7989 and https://github.com/mitodl/learn-ai/pull/276
- Only includes `citation_url` and `citation_title` attributes in content file search results if `citation_url` is not null.
- Tweaks the citation prompt to reduce the frequency of hallucinatory urls and incorrect citation formats (based on a mix of experimentation and AI prompt improvement suggestions).
Set the following in `backend.local.env`:
- CANVAS_TUTOR_DEMO_RUN_READABLE_IDS=["14566-kaleba:20211202+canvas", "34642-15.095_FA25"]
- AI_CITED_PROMPTS=["syllabus", "syllabus_canvas"]
- Disable any lansgmith env values
Go to the following urls:
- http://ai.open.odl.local:8003/?rec_prompt=&tab=SyllabusCanvasGPT&syllabus_prompt=&syllabus_canvas_prompt= : canvas course with citation urls.  Ask …
=> Better citations

ai_chatbots/consumers.py, ai_chatbots/consumers_test.py, ai_chatbots/serializers.py
closes https://github.com/mitodl/hq/issues/8233
The canvas tutor chat does not currently populate the object id. This fixes the issue
Go to the Canvas Tutor bot tab and start a new thread
Write a message to the bot
from the shell run
```
from ai_chatbots.models import *
UserChatSession.objects.last().__dict__
```
the `object_id` field should not be blank
=> fix object id for canvas totur bot

ai_chatbots/api.py, ai_chatbots/api_test.py, ai_chatbots/checkpointers.py, ai_chatbots/checkpointers_test.py, ai_chatbots/constants.py
Follow-up to https://github.com/mitodl/learn-ai/pull/301
Rachel noticed that the child key for `writes` in the metadata should differ based on the message type: `__start__` for human messages, `tools` for tool messages, `ai` for AI messages.   The code was always using `__start__`, this PR fixes that.
- You can revert the last ai_chatbots migration and then rerun, then look at the checkpoints created for `TutorBotOutputs`.  
- For human message checkpoints, the metadata `writes` attribute should start with `"__start__": {"messages":`.
- For ai message checkpoints, the metadata `writes` attribute should start with `"agent": {"messages":`.
- Use the tutorbot and at least one other bot to ask questions, then view the checkpoints' metadata for each.  
- For human message checkpoints, the …
=> Adjust metadata writes

ai_chatbots/api.py, ai_chatbots/api_test.py, ai_chatbots/management/commands/backpopulate_tutor_checkpoints.py
Related to https://github.com/mitodl/learn-ai/pull/301
Tweaks TutorBotOutput checkpoint data to be more in line with other bot checkpoints
- Start a new thread using either tutor bot, ask a series of questions.
- Check that there are 2 checkpoints created for each `TutorBotOutput`,  the `DjangoCheckpoint.checkpoint` message format matches the `DjangoCheckpoint.metadata` messages format, and all `step` values are sequential.
- If you have preexisting `TutortBotOutputs`, run `./manage.py backpopulate_tutor_checkpoints --overwrite` and verify the above for all `TutorBotOutputs`
=> Tweak  checkpoint data for TutorBotOutput

frontend-demo/.yarnrc.yml
_This PR was generated automatically via a script._
This PR disables yarn's postinstall scripts by setting `enableScripts: false` in `.yarnrc.yml`. It is part of:
- https://github.com/mitodl/hq/issues/8676
Disabling postinstall scripts improves security by:
- **Preventing malicious code execution**: Stops potentially harmful scripts from running during package installation
- **Supply chain security**: Reduces risk from compromised packages that could execute malicious postinstall scripts
- **Controlled execution**: Allows manual review and execution of necessary scripts only when needed
- Added `enableScripts: false` to `.yarnrc.yml`
- Some packages may require manual script execution if they depend on postinstall hooks
- Improved security posture against supply chain attacks
- No …
=> Security: Disable yarn postinstall scripts

README.md, ai_chatbots/chatbots.py, ai_chatbots/conftest.py, ai_chatbots/evaluation/base.py, ai_chatbots/evaluation/base_test.py, ai_chatbots/evaluation/evaluators.py, ai_chatbots/evaluation/evaluators_test.py, ai_chatbots/evaluation/orchestrator.py, ai_chatbots/evaluation/orchestrator_test.py, ai_chatbots/evaluation/reporting.py, ai_chatbots/evaluation/reporting_test.py, ai_chatbots/evaluation/timeout_wrapper.py, ai_chatbots/evaluation/timeout_wrapper_test.py, ai_chatbots/management/commands/convert_eval_csv_to_json.py, ai_chatbots/management/commands/rag_evaluation.py, main/settings.py
Related to https://github.com/mitodl/hq/issues/7605
- Adds a few options to the `rag_evaluation` management command:
- a data file to read test cases from
- an output file to write to
- a timeout value to abort an individual test case (test cases were sometimes hanging and preventing the evalutation from completing)
- a concurrency value to specify how many tests should run in parallel
- Adds error and async configs to allow the evaluation to proceed if individual test cases raise an exception, and to allow tests to run simultaneously
- Fixes incorrect summary statistics caused by certain metrics (i.e. hallucination) having an inverse score where 0 = best, 1 = worst, instead of the other way around.
Run the mgmt command and try out some of the new options, for example:
```bash
./manage.py …
```
=> Enhancements to RAG evaluation command
